import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation"; // 💡 리디렉션을 위한 Next.js 서버 유틸리티
import { headers } from "next/headers"; // 💡 현재 경로를 확인하기 위한 서버 유틸리티
import { handleLoginChk } from "@/app/serveraction/loginchk/loginchkaction";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 1. RootLayout 함수를 async로 선언합니다.
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 2. 현재 경로를 서버에서 확인합니다.
  const headersList = headers();
  // 'x-pathname' 헤더는 요청된 경로를 담고 있습니다.
  const pathname = headersList.get("x-pathname"); 
  // 리디렉션 대상 경로를 정의합니다. (실제 로그인 페이지 경로로 변경)
  const loginPath = "/auth/login"; 
  
  // 3. 서버 함수를 호출하여 로그인 상태를 확인합니다.
  // handleLoginChk는 사용자 ID(문자열) 또는 null을 반환합니다.
  const userId = await handleLoginChk(); 
  
  // 4. 로그인 체크 및 리디렉션 로직을 실행합니다.
  // userId가 null이고 (로그아웃 상태) 현재 경로가 로그인 페이지가 아니라면 리디렉션!
  if (!userId && pathname !== loginPath) {
    // redirect()는 내부적으로 Next.js에게 리디렉션 응답을 보내도록 지시합니다.
    redirect(loginPath);
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}